Repository omise/omise-php, pull requests merged in 2019-01, with the labels that each got.

#102 Fix missing commits on dev-3-0-0 branch
  lib/Omise.php
  lib/omise/ApiRequestor.php
  lib/omise/Http/Response/Handler.php
  lib/omise/OmiseAccount.php
  lib/omise/OmiseBalance.php
  lib/omise/OmiseCard.php
  lib/omise/OmiseCardList.php
  lib/omise/OmiseCharge.php
  lib/omise/OmiseCustomer.php
  lib/omise/OmiseDispute.php
  lib/omise/OmiseEvent.php
  lib/omise/OmiseForex.php
  lib/omise/OmiseLink.php
  lib/omise/OmiseOccurrence.php
  lib/omise/OmiseRecipient.php
  lib/omise/OmiseRefundList.php
  lib/omise/OmiseSchedule.php
  lib/omise/OmiseSearch.php
  lib/omise/OmiseSource.php
  lib/omise/OmiseToken.php
  lib/omise/OmiseTransaction.php
  lib/omise/OmiseTransfer.php
  lib/omise/res/OmiseApiResource.php
  tests/omise/ApiRequestorTest.php
  tests/omise/Http/Response/HandlerTest.php
Labels: project: 3.x

#101 Officially dropping support of PHP v5.3
  README.md
  composer.json
Labels: Status: Ready, project: 2.x

#100 Introducing Capability API
  lib/Omise.php
  lib/omise/OmiseCapabilities.php
  lib/omise/res/OmiseApiResource.php
  tests/fixtures/api.omise.co/capability-get.json
  tests/omise/CapabilitiesTest.php
Labels: Status: Ready, Type: Feature, project: 2.x

#106 Fixes issue with use of array constant (mandated PHP 5.6+)
  lib/omise/OmiseCapabilities.php
Labels: Status: Review Needed, Type: Bug, project: 2.x

#103 Introducing Namespace
  composer.json
  lib/Account.php
  lib/Balance.php
  lib/Card.php
  lib/CardList.php
  lib/Charge.php
  lib/Customer.php
  lib/Dispute.php
  lib/Event.php
  lib/Forex.php
  lib/Link.php
  lib/Occurrence.php
  lib/OccurrenceList.php
  lib/Omise.php
  lib/Recipient.php
  lib/Refund.php
  lib/RefundList.php
  lib/Schedule.php
  lib/ScheduleList.php
  lib/Scheduler.php
  lib/Search.php
  lib/Source.php
  lib/Token.php
  lib/Transaction.php
  lib/Transfer.php
  lib/omise/OmiseAccount.php
  lib/omise/OmiseBalance.php
  lib/omise/OmiseCard.php
  lib/omise/OmiseCardList.php
  lib/omise/OmiseCharge.php
  lib/omise/OmiseCustomer.php
  lib/omise/OmiseDispute.php
  lib/omise/OmiseEvent.php
  lib/omise/OmiseForex.php
  lib/omise/OmiseLink.php
  lib/omise/OmiseOccurrence.php
  lib/omise/OmiseOccurrenceList.php
  lib/omise/OmiseRecipient.php
  lib/omise/OmiseRefund.php
  lib/omise/OmiseRefundList.php
  lib/omise/OmiseSchedule.php
  lib/omise/OmiseScheduleList.php
  lib/omise/OmiseScheduler.php
  lib/omise/OmiseSearch.php
  lib/omise/OmiseSource.php
  lib/omise/OmiseTest.php
  lib/omise/OmiseToken.php
  lib/omise/OmiseTransaction.php
  lib/omise/OmiseTransfer.php
  lib/omise/res/OmiseApiResource.php
  lib/omise/res/OmiseVaultResource.php
  lib/omise/res/obj/OmiseObject.php
  tests/omise/ClassExistsTest.php
Labels: Status: Ready, Type: Feature, project: 3.x
